<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<!-- The following viewport is needed so the video and page auto maximizes to the viewport display -->
<meta name="viewport" content="width=device-width, initial-scale=1" />
<!-- This file is the default HTML template used by the troubleshooting step-by-step pages. -->
<!-- footer1.inc contains the closing tags for this header. -->
<title>Magic Square School Tools</title>
<link rel="stylesheet" href="stylesregular.css" type="text/css" />
</head>
<body>
<div id="wrapper">
