<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <!-- Maximize the content on the current viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- This file is the default HTML template used by the pages in the app. -->
    <!-- footer1.inc contains the closing tags for this header. -->
    <title>Magic Square Quiz Maker</title>
    <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="styles.css" type="text/css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  </head>
  <body>
